# Site settings
title: "kkkkk"
description: "to say a few words"
baseurl: ""
url: "https://thisiskaychen.github.io"

# Author
author:
  name: Kay Chen
  url: "https://thisiskaychen.github.io"
  email: kayc010804@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

permalink: /:year-:month-:day/:title
paginate: 5

exclude: [Gemfile, Gemfile.lock, tale.gemspec]

excerpt_separator: <!--more-->
